services:
  - type: web
    name: smart-workplace-assistant
    env: python
    buildCommand: pip install -r requirements.txt && python scripts/setup_database.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
